import pytest
import tempfile
import os
from io import BytesIO, StringIO
from pyhmmer import easel
from pyhmmer.plan7 import HMM
from domainator.hmmer_build import hmmer_build, main
from domainator.utils import pyhmmer_decode
from pathlib import Path


@pytest.fixture
def msa_content():
    return b">seq1\nACGTACGT\n>seq2\nACGTACGA\n"

def create_msa_file(content):
    with tempfile.NamedTemporaryFile(delete=False, mode="wb") as f:
        f.write(content)
        return f.name

@pytest.fixture
def msa_file(msa_content):
    file_path = create_msa_file(msa_content)
    yield file_path
    os.unlink(file_path)

def test_hmmer_build_with_required_params():
    msa_content = b">seq1\nACGTACGT\n>seq2\nACGTACGA\n"
    msa_file = create_msa_file(msa_content)

    with open(msa_file, "rb") as file:
        hmm = hmmer_build(file, name="test_profile")
        assert isinstance(hmm, HMM)
        assert pyhmmer_decode(hmm.name) == "test_profile"

    os.unlink(msa_file)

def test_hmmer_build_with_optional_params():
    msa_content = b">seq1\nACGTACGT\n>seq2\nACGTACGA\n"
    msa_file = create_msa_file(msa_content)

    with open(msa_file, "rb") as file:
        hmm = hmmer_build(file, name="test_profile", acc="P12345", desc="Test profile description", alphabet=easel.Alphabet.dna())
        assert isinstance(hmm, HMM)
        assert pyhmmer_decode(hmm.name) == "test_profile"
        assert pyhmmer_decode(hmm.accession) == "P12345"
        assert pyhmmer_decode(hmm.description) == "Test profile description"

    os.unlink(msa_file)

def test_hmmer_build_with_binaryio():
    msa_content = b">seq1\nACGTACGT\n>seq2\nACGTACGA\n"
    msa_file = BytesIO(msa_content)

    hmm = hmmer_build(msa_file, name="test_profile", acc="P12345", desc="Test profile description", alphabet=easel.Alphabet.dna())
    assert isinstance(hmm, HMM)
    assert pyhmmer_decode(hmm.name) == "test_profile"
    assert pyhmmer_decode(hmm.accession) == "P12345"
    assert pyhmmer_decode(hmm.description) == "Test profile description"


def test_main_with_required_params(msa_file, capsys):
    main(["--name", "test_profile", "--input", msa_file])
    captured = capsys.readouterr()
    assert "HMMER3/f" in captured.out
    assert "NAME  test_profile" in captured.out

def test_main_with_optional_params(msa_file, capsys):
    main(["--name", "test_profile", "--acc", "P12345", "--desc", "Test profile description", "--input", msa_file, "--alphabet", "dna"])
    captured = capsys.readouterr()
    output = captured.out
    assert "HMMER3/f" in output
    assert "NAME  test_profile" in output
    assert "ACC   P12345" in output
    assert "DESC  Test profile description" in output



# --- DNA / RNA alphabets --------------------------------------------------
#
# The .afa fixtures were generated by test/data/README_alphabet_fixtures.md;
# the .hmm fixtures were built from them with hmmer_build.py itself.

def _build(shared_datadir, args):
    with tempfile.TemporaryDirectory() as output_dir:
        out_path = os.path.join(output_dir, "out.hmm")
        main(args + ["-o", out_path])
        return Path(out_path).read_text()


def test_hmmer_build_dna_alphabet(shared_datadir):
    text = _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d", "--alphabet", "dna"])
    assert "ALPH  DNA" in text
    assert "MAXL  " in text


def test_hmmer_build_rna_alphabet(shared_datadir):
    text = _build(shared_datadir, ["-i", str(shared_datadir / "rna_msa_1.afa"), "--name", "r", "--alphabet", "rna"])
    assert "ALPH  RNA" in text


def test_hmmer_build_infers_dna_and_rna(shared_datadir):
    assert "ALPH  DNA" in _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d"])
    assert "ALPH  RNA" in _build(shared_datadir, ["-i", str(shared_datadir / "rna_msa_1.afa"), "--name", "r"])


def test_hmmer_build_window_length_sets_maxl(shared_datadir):
    default_text = _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d", "--alphabet", "dna"])
    forced_text = _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d", "--alphabet", "dna", "--window_length", "500"])
    assert "MAXL  500" not in default_text
    assert "MAXL  500" in forced_text


def test_hmmer_build_window_beta_changes_maxl(shared_datadir):
    default_text = _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d", "--alphabet", "dna"])
    beta_text = _build(shared_datadir, ["-i", str(shared_datadir / "dna_msa_1.afa"), "--name", "d", "--alphabet", "dna", "--window_beta", "1e-3"])
    default_maxl = [l for l in default_text.splitlines() if l.startswith("MAXL")][0]
    beta_maxl = [l for l in beta_text.splitlines() if l.startswith("MAXL")][0]
    assert default_maxl != beta_maxl


def test_hmmer_build_window_length_rejected_for_amino():
    # pyhmmer silently accepts window_length for an amino alphabet, so nothing but this
    # check stands between the user and a meaningless setting.
    msa_file = BytesIO(b">seq1\nMKVLAAGIVGLSTAAQLAKR\n>seq2\nMKVLGAGIVGLSTAAQLAKR\n")
    with pytest.raises(ValueError, match="nucleotide"):
        hmmer_build(msa_file, name="p", window_length=200)


def test_hmmer_build_window_length_and_beta_mutually_exclusive(shared_datadir):
    with pytest.raises(ValueError, match="Only one of window_length and window_beta"):
        hmmer_build(str(shared_datadir / "dna_msa_1.afa"), name="d", window_length=200, window_beta=1e-3)


def test_hmmer_build_ambiguous_alphabet_error_mentions_flag():
    # Too few columns for pyhmmer to guess the alphabet.
    with pytest.raises(ValueError, match="--alphabet"):
        hmmer_build(BytesIO(b">seq1\nAC\n>seq2\nAC\n"), name="x")


def test_hmmer_build_empty_input_raises():
    # MSAFile segfaults the interpreter on an empty stream under pyhmmer 0.12.1, so this
    # guard is what keeps empty stdin (and this test session) from taking the process down.
    with pytest.raises(ValueError, match="empty"):
        hmmer_build(BytesIO(b""), name="x")


def test_hmmer_build_unnamed_msa_raises():
    with pytest.raises(ValueError, match="unnamed"):
        hmmer_build(BytesIO(b">seq1\nACGTACGTACGTACGTACGTAC\n>seq2\nACGTACGTTCGTACGTACGTAC\n"))
