name: domainator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.14
  - pip>=23.3
  - setuptools>=61.0.0
  - cd-hit>=4.8.1,<5.0
  - diamond>=2.0.0,<3.0
  - hmmer>=3.3.2,<4.0
  - usearch>=12.0_beta,<13.0
  - pip:
    - -e .[test]
