name: domainator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip>=23.3
  - setuptools>=61.0.0
  - cd-hit~=4.8.1
  - diamond>=2.0.0
  - hmmer~=3.3.2
  - usearch
  - pip:
    - -e .[test]

