import argparse
__version__ = "0.7.1"     # remember to update version in README.md also. And if you make breaking changes to the matrix file format, increment the matrix file version in data_matrix.py.
DOMAIN_FEATURE_NAME="Domainator" # Changing this will break backwards compatibility with files generated by other versions of Domainator
DOMAIN_SEARCH_BEST_HIT_NAME="Domain_Search" # Changing this will break backwards compatibility with files generated by other versions of Domainator
# SYS_ANNOTATION_NAME="Domainator_sys_" #Changing this will (probably) NOT break backwards compatibility with files generated by other versions of Domainator

class RawAndDefaultsFormatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawTextHelpFormatter):
    pass

